Repository wrappid/wrappid-app, pull requests merged in 2024-01, with the labels that each got.

#16 fix: :bug: fixing StaticWebPage for mobile devices
  src/components/StaticWebPage.js
Labels: bug

#18 feat: ✨ : update wrappid-app template
  .github/workflows/pr-guardrails.yml
  src/components/StaticWebPage.js
Labels: enhancement

#20 feat: :sparkles: Added wrappid-app version details
  src/components/layouts/WrappidAppLayout.js
Labels: enhancement

#22 feat: :sparkles: Added buttons to navigate to styles and components p…
  src/components/StaticWebPage.js
Labels: enhancement

#24 docs: contributing rules
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: documentation, enhancement

#25 feat: ✨ : update wrappid-app template
  .github/pull_request_template.md
  .github/workflows/pr-guardrails.yml
  CONTRIBUTING.md
  src/components/StaticWebPage.js
  src/components/layouts/WrappidAppLayout.js
Labels: enhancement

#28 feat: ✨ : update wrappid-app template
  .github/pull_request_template.md
  .husky/commit-msg
  .husky/pre-commit
  .vscode/settings.json
  commitlint.config.js
  lint-staged.config.js
  package-lock.json
  package.json
  src/components/StaticWebPage.js
  src/index.js
  src/registry/ResourcesRegistry.js
  src/styles/AppClasses.js
Labels: enhancement

#30 docs: 🔒 license added
  LICENSE
Labels: documentation

#37 docs: :memo: changes in package.json
  package-lock.json
  package.json
Labels: enhancement
