Repository wrappid/wrappid-app, pull requests merged in 2024-02, with the labels that each got.

#41 refactor(core): :art: styles files consistency for modules styles sup…
  src/styles/DefaultAppStyles.js
  src/styles/LargeAppStyles.js
  src/styles/MediumAppStyles.js
  src/styles/SmallAppStyles.js
  src/styles/XLargeAppStyles.js
  src/styles/XXLargeAppStyles.js
  src/styles/index.js
  src/styles/modules/DefaultModulesStyles.js
  src/styles/modules/LargeModulesStyles.js
  src/styles/modules/MediumModulesStyles.js
  src/styles/modules/SmallModulesStyles.js
  src/styles/modules/XLargeModulesStyles.js
  src/styles/modules/XXLargeModulesStyles.js
Labels: refactor

#44 fix: :fire: remove 'usingSmallUtilityStyles' from styles files
  src/styles/DefaultAppStyles.js
  src/styles/LargeAppStyles.js
  src/styles/MediumAppStyles.js
  src/styles/SmallAppStyles.js
  src/styles/XLargeAppStyles.js
  src/styles/XXLargeAppStyles.js
Labels: bug

#39 Wrpd enhancement 32
  src/components/PackageList.js
  src/components/layouts/WrappidAppLayout.js
  src/registry/ComponentsRegistry.js
  src/registry/ResourcesRegistry.js
  src/registry/RoutesRegistry.js
Labels: bug

#48 fix(core): :zap: update component name and other impact handles
  .eslintrc.js
  src/components/About.js
  src/components/layouts/WrappidAppLayout.js
  src/registry/ComponentsRegistry.js
  src/registry/RoutesRegistry.js
Labels: bug

#50 feat(core): :sparkles: project title and description added
  src/components/StaticWebPage.js
Labels: enhancement

#52 fix(core): ⚡ update component name and other impact handles
  src/components/StaticWebPage.js
Labels: bug

#53 fix(core): ⚡ update component name and other impact handles
  src/components/About.js
  src/registry/ComponentsRegistry.js
  src/registry/RoutesRegistry.js
Labels: bug

#54 merge: development to main
  src/components/About.js
  src/registry/ComponentsRegistry.js
  src/registry/RoutesRegistry.js
Labels: bug

#56 Wrpd enhancement 32
  src/components/About.js
Labels: bug

#55 added styles, component and other additional details
  src/components/StaticWebPage.js
  src/components/layouts/WrappidAppLayout.js
Labels: bug

#58 feat(core): :sparkles: styling and UI related changes
  src/components/StaticWebPage.js
Labels: enhancement

#59 merge: from Development
  src/components/About.js
  src/components/StaticWebPage.js
Labels: enhancement

#61 fix(global): :bug: remove homepage key
  package.json
Labels: bug

#63 feat(global): :sparkles: added staticWebPageContent.js and style changes
  src/components/StaticWebPage.js
  src/components/StaticWebPageContent.js
Labels: enhancement

#64 merge: from Development
  src/components/About.js
  src/components/StaticWebPage.js
  src/components/StaticWebPageContent.js
  src/components/layouts/WrappidAppLayout.js
  src/registry/RoutesRegistry.js
Labels: enhancement

#66 style(core): :art: changes made to ui
  src/components/StaticWebPageContent.js
Labels: enhancement

#70 ci(config): :wrench: add sample worflows
  .github/workflows/app-deploy.yml.NOT_IN_USE
  .github/workflows/create-release.yml.NOT_IN_USE
  .github/workflows/create-tag.yml.NOT_IN_USE
Labels: enhancement

#71 merge: from Development
  .github/workflows/app-deploy.yml.NOT_IN_USE
  .github/workflows/create-release.yml.NOT_IN_USE
  .github/workflows/create-tag.yml.NOT_IN_USE
Labels: enhancement

#74 enhancement: improve pre-commit condition
  .husky/pre-commit
Labels: enhancement

#80 dependency: :arrow_up: update eslint-plugin-etc
  package-lock.json
  package.json
Labels: dependency

#82 refactor(core): :zap: removed default theme from wrappid.conf.json
  wrappid.conf.json
Labels: clean-up

#83 fix(core): :recycle: fullstop added to the project description
  src/components/StaticWebPageContent.js
Labels: enhancement

#86 enhancement: pr guardrails and package.json dependencies.
  .github/workflows/pr-guardrails.yml
  .gitignore
  package-lock.json
  package.json
Labels: enhancement
