Repository wrappid/wrappid-app, pull requests merged in 2024-03, with the labels that each got.

#89 ci(config): 🔧 update ci config for deploy
  .github/workflows/app-deploy.yml.NOT_IN_USE
  .gitignore
Labels: enhancement

#90 enhancement: layout related fix
  src/App.js
  src/components/About.js
  src/components/AppComponent.js
  src/components/AppComponentContent.js
  src/components/Layouts.js
  src/components/StaticWebPage.js
  src/components/layouts/AppDrawerLayout.js
  src/components/layouts/WrappidAppLayout.js
  src/registry/ComponentsRegistry.js
  src/registry/RoutesRegistry.js
  wrappid.conf.json
Labels: enhancement

#91 merge: from Development
  src/App.js
  src/components/About.js
  src/components/AppComponent.js
  src/components/AppComponentContent.js
  src/components/Layouts.js
  src/components/StaticWebPage.js
  src/components/layouts/AppDrawerLayout.js
  src/components/layouts/WrappidAppLayout.js
  src/registry/ComponentsRegistry.js
  src/registry/RoutesRegistry.js
  wrappid.conf.json
Labels: enhancement

#92 bugfix: themes & section related update
  src/components/AppComponentContent.js
  src/components/AppComponentSection.js
  src/registry/RoutesRegistry.js
  src/registry/ThemesRegistry.js
  src/themes/theme2.json
  src/themes/theme3.json
Labels: enhancement

#95 enhancement: add missing wrappid packages key
  .wrappid/wrappid.meta.json
  package-lock.json
  package.json
Labels: enhancement

#96 chore: development support added to wrappid app for handing layout manager
  package-lock.json
  src/components/AppComponentContent.js
  src/components/layouts/ComplexLayout.js
  src/components/layouts/ComplexLayoutPage.js
  src/components/layouts/CoreLayoutItem.js
  src/components/layouts/CoreLayoutPlaceholder.js
  src/components/layouts/LayoutManager.js
  src/components/layouts/LayoutManagerTest.js
  src/registry/ComponentsRegistry.js
  src/registry/RoutesRegistry.js
Labels: enhancement

#97 enhancement: version details fetched from related package.json
  src/components/AppComponentContent.js
  src/components/AppComponentSection.js
  src/registry/ComponentsRegistry.js
Labels: enhancement

#101 ci: wrappid-app template versioning
  .github/workflows/create-tag.yml
  .wrappid/wrappid.meta.json
Labels: enhancement

#102 fix: :bug: fix the texts
  src/components/AppComponentContent.js
  src/components/AppComponentSection.js
Labels: bug

#104 bug: boilerplate page ui
  src/components/AppComponentContent.js
  src/components/AppComponentSection.js
  src/components/layouts/WrappidAppLayout.js
Labels: bug

#106 feat(utils): 📝 add script to generate attribution
  ATTRIBUTIONS.md
  package-lock.json
  package.json
  scripts/attributions.gen.js
Labels: enhancement

#108 chore(config): :lock: fix runtime security issues
  package-lock.json
Labels: security

#110 bugfix: :bug: fix eslint pr guardrails
  .github/workflows/pr-guardrails.yml
Labels: bugfix

#111 enhancement: removing strict mode from index and moved to core
  src/index.js
  src/registry/RoutesRegistry.js
Labels: enhancement
